services:
    api:
        build:
            context: ./api
            dockerfile: Dockerfile.dev
        ports:
            - 5000:5000
        volumes:
            - ./api:/app
            - api_bin:/app/bin
            - api_obj:/app/obj
        depends_on:
            - db
    
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        ports:
            - 3000:3000
        volumes:
            - ./frontend:/app
            - frontend_node_modules:/app/node_modules
        depends_on:
            - api

    db: 
        image: postgres:13-alpine3.21
        environment:
            POSTGRES_DB: ticketing_system
            POSTGRES_PASSWORD: secret
        volumes:
            - postgres-data:/var/lib/postgresql/data
    
    db_visualizer:
        image: dpage/pgadmin4:8.4
        environment:
            PGADMIN_DEFAULT_EMAIL: user@gmail.com
            PGADMIN_DEFAULT_PASSWORD: secret
        ports:
            - 8888:80
        depends_on:
            - db
        volumes:
            - /var/lib/pgadmin
            

volumes:
    frontend_node_modules:
    postgres-data:
    api_bin:
    api_obj: