FROM mcr.microsoft.com/dotnet/sdk:8.0

RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"

WORKDIR app/


COPY *.csproj .
RUN dotnet restore

COPY . .
ENTRYPOINT ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:5000"]